version: '3.6'
services:

  express:
    build: ./
    container_name: express
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WAIT_HOSTS=rabbitmq:5672
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=10
      - WAIT_HOST_CONNECT_TIMEOUT=30
    ports:
      - 3001:3000
    volumes:
      - .:/src
    restart: on-failure
    depends_on:
      - rabbitmq
    command: sh -c "/wait && node src/app.js"
  
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    expose:
      - "27017"

  rabbitmq:
    image: "rabbitmq:3.8-management-alpine"
    container_name: nodejs-rabbitmq
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - "./.rabbitmq_data:/var/lib/rabbitmq/mnesia"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
